Repository MatheusHenriqueSS/maratonic, pull requests merged in 2023-06, with the labels that each got.

#40 Feature/create authentication system
  .github/workflows/github-actions.yml
  .gitignore
  .npmrc
  app/_app.jsx
  app/api/__tests__/repositories/categories.test.ts
  app/api/__tests__/repositories/images.test.ts
  app/api/__tests__/repositories/posts.test.ts
  app/api/__tests__/repositories/problems.test.ts
  app/api/__tests__/repositories/users.test.ts
  app/api/auth/[...nextauth]/route.ts
  app/api/categories.ts
  app/api/controllers/categories.ts
  app/api/controllers/images.ts
  app/api/controllers/posts.ts
  app/api/controllers/problems.ts
  app/api/controllers/users.ts
  app/api/images.ts
  app/api/login/route.ts
  app/api/mock.ts
  app/api/posts.ts
  app/api/problems.ts
  app/api/repositories/categories.ts
  app/api/repositories/images.ts
  app/api/repositories/posts.ts
  app/api/repositories/problems.ts
  app/api/repositories/users.ts
  app/api/users.ts
  app/components/MainPage/MainPage.tsx
  app/components/Nav/Nav.module.css
  app/components/Nav/Nav.tsx
  app/components/Nav/links.ts
  app/components/buttons.component.tsx
  app/components/toast.component.tsx
  app/components/user.component.tsx
  app/layout.tsx
  app/lib/prisma.ts
  app/login/form.tsx
  app/login/page.tsx
  app/page.tsx
  app/providers.tsx
  components/toast.component.tsx
  lib/prisma.ts
  middleware.ts
  package.json
  prisma/schema.prisma
  public/github.svg
  public/google.svg
  tsconfig.json
Labels: enhancement, AvaliacaoA2

#48 Update architecture
  README.md
  app/api/categories.ts
  app/api/controllers/categories.ts
  app/api/controllers/controller.ts
  app/api/controllers/images.ts
  app/api/controllers/posts.ts
  app/api/controllers/problems.ts
  app/api/controllers/users.ts
  app/api/images.ts
  app/api/posts.ts
  app/api/problems.ts
  app/api/users.ts
  app/components/Nav/Nav.tsx
  app/components/Nav/links.ts
  app/components/buttons.component.tsx
  app/components/user.component.tsx
  app/layout.tsx
  architecture_diagram/diagram.pdf
  components/toast.component.tsx
Labels: documentation, AvaliacaoA4.1

#50 feat: update nav bar
  app/_app.jsx
  app/api/auth/[...nextauth]/route.ts
  app/api/controllers/images.ts
  app/api/controllers/problems.ts
  app/components/Nav/Nav.module.css
  app/components/Nav/Nav.tsx
  app/components/Nav/icons/brush.svg
  app/components/Nav/icons/plus.svg
  app/components/Nav/links.ts
  app/page.tsx
  types/next-auth.d.ts
Labels: enhancement

#51 fix: fix wrong api routes implementation
  app/api/[table]/route.ts
  app/api/categories.ts
  app/api/controllers/categories.ts
  app/api/controllers/controller.ts
  app/api/controllers/images.ts
  app/api/controllers/posts.ts
  app/api/controllers/problems.ts
  app/api/controllers/users.ts
  app/api/images.ts
  app/api/posts.ts
  app/api/problems.ts
  app/api/repositories/categories.ts
  app/api/repositories/images.ts
  app/api/repositories/posts.ts
  app/api/repositories/problems.ts
  app/api/repositories/users.ts
  app/api/users.ts
  prisma/schema.prisma
Labels: bug

#53 Feature/create class post editor
  app/api/controllers/posts.ts
  app/api/repositories/posts.ts
  app/components/Nav/links.ts
  app/editor/page.tsx
  app/page.tsx
  next.config.js
  package-lock.json
  package.json
Labels: enhancement

#54 Feature/create search post page
  app/classes/[id]/page.tsx
  app/classes/page.tsx
  app/components/Nav/Nav.module.css
  app/components/Nav/Nav.tsx
  app/components/SearchBar/SearchBar.module.css
  app/components/SearchBar/SearchBar.tsx
  app/components/SearchPostPage/Card.module.css
  app/components/SearchPostPage/SearchPostPage.module.css
  app/components/SearchPostPage/SearchPostPage.tsx
Labels: enhancement

#56 Feature/render classes page
  app/classes/[id]/page.tsx
  app/editor/page.tsx
  package-lock.json
  package.json
Labels: enhancement

#55 Feature/create profile page
  app/api/controllers/problems.ts
  app/api/repositories/problems.ts
  app/api/repositories/users.ts
  app/components/MainPage/MainPage.module.css
  app/components/profileContainer/__tests__/getRanking.test.ts
  app/components/profileContainer/getRanking.ts
  app/components/profileContainer/profileContainer.module.css
  app/components/profileContainer/profileContainer.tsx
  app/components/profileContainer/rankingIcons/diamante.png
  app/components/profileContainer/rankingIcons/grao_mestre.png
  app/components/profileContainer/rankingIcons/marrom.png
  app/components/profileContainer/rankingIcons/mestre.png
  app/components/profileContainer/rankingIcons/ouro.png
  app/components/profileContainer/rankingIcons/platina.png
  app/components/profileContainer/rankingIcons/prata.png
  app/components/profileContainer/rankingIcons/preto.png
  app/profile/page.tsx
  middleware.ts
  prisma/schema.prisma
Labels: enhancement, AvaliacaoA2
